name: Build Ubuntu

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          cd painter
          python -m pip install --upgrade pip setuptools wheel
          python -m venv env
          source env/bin/activate
          pip install "pyinstaller==6.6.0"
          pip install -r requirements.txt

      - name: Build software
        run: |
          cd painter
          source env/bin/activate
          python src/build/run_pyinstaller.py

      - name: Make installer
        run: |
          cd painter
          bash src/build/make_deb_file.sh

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: Package-ubuntu-22.04
          path: ${{ github.workspace }}/painter/dist/RootPainter.deb
          if-no-files-found: error

