name: Build OSX

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-14
            arch: arm64
          - os: macos-15-intel
            arch: x86_64

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python '3.11'
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        cd painter
        brew install create-dmg
        python -m pip install --upgrade pip
        python -m venv env
        source env/bin/activate
        pip install "pyinstaller==6.6.0"
        pip install -r requirements.txt

    - name: Build software
      run: |
        cd painter
        source env/bin/activate
        python src/build/run_pyinstaller.py

    - name: Make installer
      run: |
        cd painter
        pkgbuild --component dist/RootPainter.app --install-location /Applications dist/RootPainter.pkg

    - name: Rename package with arch
      run: |
        cd painter/dist
        mv RootPainter.pkg RootPainter-${{ matrix.arch }}.pkg

    - name: Upload package
      uses: actions/upload-artifact@v4
      with:
        name: Package-${{ matrix.arch }}
        path: ${{github.workspace}}/painter/dist/RootPainter-${{ matrix.arch }}.pkg
        if-no-files-found: error

